version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=devlopment
            - MONGO_USER=lekan
            - MONGO_PASSWORD=dockernodeapppassword
        command: npm run dev
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=lekan
            - MONGO_INITDB_ROOT_PASSWORD=dockernodeapppassword